### ISSUE TITLE
Swift port just published.

### ISSUE THREAD

**Issue by profburke** [WaniKani/WanaKana#106]
I have ported the library to Swift(*) and have used it in a few of my iOS apps. Recently, I thought I would make the code available and would appreciate it if you could link to it in your README.

My repo is at https://github.com/profburke/WanaKanaSwift/

Also, if possible, can it be linked from https://wanakana.com/ -- I notice the Python port is listed there, so it may be you don't have access to edit that site.

Regards,

Matt

(*)To be completely honest, it's not so much a port as I have wrapped your JavaScript code using Apple's JavaScript Core library. I'm working on a complete re-write in Swift, but not quite finished yet.

**Comment by DJTB** [comment]
Thanks for contributing Matt! 🥇
I've updated the readme and website to include your port - let us know if you finish the re-write and I'll update it again.
