### ISSUE TITLE
Option to output romaji with spaces (or as array?) to show for ruby-text

### ISSUE THREAD

**Issue by sudofox** [WaniKani/WanaKana#118]
## Issue Type
Feature

## Description

When using Wanakana to produce romaji for furigana, we should have an option to split the output romaji with spaces so that the ruby-text distributes them evenly to display above the proper characters.

While splitting the input text into space-separated characters (`.split("").join(" ")`) before turning it into romaji sort of works, it causes other text to be split that shouldn't (e.g "Twitter" becomes "T w i t t e r")

```js
// First split the text into tokens
let splitText = tokenize(obj.text);
for (var item in splitText) {
    let romaji = toRomaji(splitText[item].split('').join(' '));
    splitText[item] = h("ruby", [splitText[item], h("rt", romaji )]);
}
```

**Comment by DJTB** [comment]
@sudofox I think what you're truly after is outside the scope of Wanakana.
Furigana isn't just evenly spaced, it should be matched to the respective kanji, with redundant romaji omitted.

I would recommend using something like https://github.com/Doublevil/JmdictFurigana to determine which romaji should be displayed above which characters. You can see an implementation in react I did a while ago here
https://djtb.github.io/react-furi/

Hope that helps!
