### ISSUE TITLE
Wanakana Support for くぃ, くぇ, くぉ

### ISSUE THREAD

**Issue by CalculusAce** [WaniKani/WanaKana#126]
## Issue Type
Wanakana Bug

## Description
I was testing Wanakana's support for typing shortcuts for a new project I am working on and discovered that the shortcuts for くぃ, くぇ, and くぉ are not currently supported in Wanakana. These shortcuts are supported by other standard IME solutions, so I think they should be implemented into Wanakana.

These shortcuts save a keystroke, since they prevent the need to type out kuxi or kuli for くぃ for example. The kwi combination should also be able to produce くぃ.

Acceptable Typing Options:

くぃ - kwi, kuxi, kuli
くぇ - kwe, kuxe, kule
くぉ - kwo, kuxo, kulo

## Steps to reproduce
Attempt to type the shortcuts for くぃ (kwi), くぇ (kwe), くぉ (kwo) and Wanakana will not succeed in producing the correct kana, regardless of mode.

* Browser: QtWebEngine

* OS/Device: Windows

* Keyboard/Input Method: toHiragana / toKatakana

**Comment by DJTB** [comment]
Thanks for the message, we'll consider adding these by default.

In the meantime, you should be able to use the custom mapping option for your desired result.
http://wanakana.com/docs/global.html#defaultOptions
```
toHiragana({ 
  customKanaMapping: { 
    kwi: 'くぃ', kuxi: 'くぃ', kuli: 'くぃ',
    kwe: 'くぇ', kuxe: 'くぇ', kule: 'くぇ',
    kwo: 'くぉ', kuxo: 'くぉ', kulo: 'くぉ'
  }
})
```

**Comment by CalculusAce** [comment]
@DJTB Thank you for considering adding those into the default conversions and for pointing out a blind spot I had in the docs that allows me to overcome the issue I was having. I will stick with the custom mapping until they are merged into the default conversions.
