### ISSUE TITLE
Option for leaving long vowel mark (ー) in toHiragana

### ISSUE THREAD

**Issue by skytomo221** [WaniKani/WanaKana#128]
## Issue Type

* [ ] Bug (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#bug-reports)
* [x] Feature (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I would like feature like this:

```js
wanakana.toHiragana('ゲーム')
// => 'げえむ'
wanakana.toHiragana('ゲーム', {convertLongVowelMark: false})
// => 'げーむ'
```

**Comment by DJTB** [comment]
This seems like a reasonable request given that long vowels aren't _always_ exclusive to katakana (e.g. らーめん).
Though given that this would usually be on a case by case basis for any given word, I wonder if it's useful as a general option.

@skytomo221  Can you explain your use-case further? It would help to determine how this should be implemented.
