### ISSUE TITLE
How to reset custom mapping?

### ISSUE THREAD

**Issue by whimsee** [WaniKani/WanaKana#129]
This probably isn't an intended use of it but I stumbled across Wanakana when I was looking for a kana -> romaji conversion tool for a project I'm working on. Basically, I just want to convert kana to readable base romaji, Hepburn w/ macrons, and other romanization systems then display them on a website.

The custom maps work like a charm, but I'm having trouble finding a way to reset or replace the mapping once it's set.

ie.  `{customRomajiMapping: {とお: "tō"}} ` works to change what would have been "too" to "tō", but I'm essentially stuck with that custom map. I can't replace it, even add to it apparently since I tried adding a silly mapping of あ to "ah" and it didn't register either.

**Comment by DJTB** [comment]
Hey @whimsee good catch!
It looks like we only apply a custom mapping if one is not already set, probably as a performance optimization.
I'll take a look at fixing this up for you.
