### ISSUE TITLE
WanaKana Browser Source Issue

### ISSUE THREAD

**Issue by CalculusAce** [WaniKani/WanaKana#136]
## Issue Type
Bug

## Description
Using https://unpkg.com/wanakana to source WanaKana for browser use results in an error occurring on this line: 

Object.defineProperty(exports, '__esModule', { value: true });

However, sourcing WanaKana from this URL works as expected: https://unpkg.com/wanakana@5.0.0/wanakana.min.js

Perhaps an unpkg field needs to be added to package.json to point to the right file, because unpkg is currently using the "main" field (cjs/index.js)?

## Steps to Reproduce
Attempt to source the latest version of WanaKana from https://unpkg.com/wanakana

# Versions
WanaKana 5.0.0

* Browser: Chrome
* OS/Device: Windows 10
* Keyboard/Input Method: All Methods

**Comment by DJTB** [comment]
Thanks for the heads up, I'll take a look later today!

**Comment by DJTB** [comment]
May take a little time to propagate, but releasing now 👍
