### ISSUE TITLE
does this include hiragana half width to hiragana full width ?

### ISSUE THREAD

**Issue by TanuAgrawal123** [WaniKani/WanaKana#150]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/WaniKani/WanaKana/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

* [ ] Bug (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#bug-reports)
* [x] Feature (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

(Add images if possible)

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

* Browser:
* OS/Device:
* Keyboard/Input Method:

**Comment by TanuAgrawal123** [comment]
query related to hirakana half-width to hirakana full-width

**Comment by DJTB** [comment]
No, it does not.

See https://en.wikipedia.org/wiki/Half-width_kana
> Half-width hiragana is not included in Unicode.
