### ISSUE TITLE
reset HTML attributes when the HTML element is unbound

### ISSUE THREAD

**Issue by scottnicolson** [WaniKani/WanaKana#152]
When an HTML element is bound the bind code adds a bunch of HTML attributes to the element: https://github.com/WaniKani/WanaKana/blob/ee3dc8750001c70e296d8022f4a433b57118ae2a/src/bind.js#L30-L35

When the element is unbound the element is not returned to its original state: https://github.com/WaniKani/WanaKana/blob/ee3dc8750001c70e296d8022f4a433b57118ae2a/src/unbind.js#L18-L19

I would like to add a PR that reverses the added attributes when the element is unbound.  Do you see any issue that this might cause?

If I was to do this, my plan would be to store any attributes that were overridden so that their original values could be reinstated, and any values that were added would be removed on unbind.

**Comment by DJTB** [comment]
This seems like a sensible addition, feel free to make a PR 👍
No issues come to mind since we're already setting the attributes regardless.
