### ISSUE TITLE
can wanakana.toKatakana() function can convert string containing both hiragana and katakana eg "タヌたぬたぬタヌ"

### ISSUE THREAD

**Issue by TanuAgrawal123** [WaniKani/WanaKana#155]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/WaniKani/WanaKana/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

* [ ] Bug (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#bug-reports)
* [ ] Feature (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

(Add images if possible)

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

* Browser:
* OS/Device:
* Keyboard/Input Method:

**Comment by DJTB** [comment]
I don't quite understand your questoin. Please provide more information in a new issue including **expected** and **actual** results, if this is still causing you trouble. Thanks.
