### ISSUE TITLE
I can't convert kanji to katakana, please fix it!!!!

### ISSUE THREAD

**Issue by slym175** [WaniKani/WanaKana#161]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/WaniKani/WanaKana/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

* [ ] Bug (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#bug-reports)
* [ ] Feature (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

(Add images if possible)

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

* Browser:
* OS/Device:
* Keyboard/Input Method:

**Comment by DJTB** [comment]
Hi there, you may misunderstand the purpose of Wanakana. It is not possible to convert kanji to katakana, to do so requires a dictionary. I can recommend the https://github.com/scriptin/jmdict-simplified project for this.

Feel free to open another issue, with more detailed information, if you have found a fault with Wanakana. Thanks!
