### ISSUE TITLE
`toRomaji('っちょ')` seems not right

### ISSUE THREAD

**Issue by ForkKILLET** [WaniKani/WanaKana#162]
## Issue Type

* [x] Bug (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#bug-reports)
* [ ] Feature (https://github.com/WaniKani/WanaKana/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

```
got: おっちょこちょい -> otchokochoi
expected: おっちょこちょい -> occhokochoi
```

## Steps to reproduce

`console.log(toRomaji('おっちょこちょい'))`

# Versions

* Browser: `Firefox 118.0b5-1`
* OS/Device: `Arch Linux x86_64 6.4.12-arch1-1`
* Keyboard/Input Method: `Anthy 9100h-6`

**Comment by IgorSzymanski** [comment]
I'm pretty sure `otchokochoi` is the correct transcription. 

https://en.wikipedia.org/wiki/Transcription_into_Japanese

Example:
キッチン kitchin
