### ISSUE TITLE
Cursor is moved to beginning when typing in Opera on Android

### ISSUE THREAD

**Issue by nibarius** [WaniKani/WanaKana#22]
How to reproduce:
1. Go to wanakana.com using Opera on Android
2. Activate the text field and type "kana"

Expected result:
The text is changed to かな

Actual result:
First か shows up, but then the cursor is moved to the front of the text field making the next letter end up first. So the result becomes なか

Additional note:
When using SwiftKey the cursor is always moved two characters back when typing one character.

When using the default google keyboard the cursor is only moved to the beginning of the text field when the cursor is initially placed after the first characters.

This does not reproduce in Chrome on the same phone with the same keyboards.

**Comment by DJTB** [comment]
@nibarius I don't suppose you still have access to the previous devices and could give this another test on the current www.wanakana.com ?

From what I've been able to test (S4, Nexus 7), newer versions of chrome/opera seem to function as expected. Hopefully this has been resolved due to modified wanakana source + browser improvements over the past 4 years.

**Comment by nibarius** [comment]
I don't have the same phone as when I originally reported this, but I've tested on my current Nexus 5x and in Opera for Android version 42.

When I'm using the default google keyboard it automatically selects the character I've inputted after conversion. So as soon as I type something else the previous text is removed.

This does not happen with the Swype keyboard. And it does not happen in Chrome (version 59) regardless of keyboard used.

**Comment by DJTB** [comment]
Thanks for the response! 

Perhaps force-clearing any selection ranges after conversion might resolve this issue.
Not sure how I'll be able to test this - I'll let you know if you can do a quick test again sometime :wink:

**Comment by DJTB** [comment]
Feel like hitting (wanakana.com)[wanakana.com] with your trusty Opera-Mini?

**Comment by nibarius** [comment]
I've tested in both the browser Opera Mini and the browser Opera for Android and wanakana.com works just fine for me.

**Comment by DJTB** [comment]
Music to my ears :+1:
