### ISSUE TITLE
[Android Chrome] First character entry results in cursor moving to the front.

### ISSUE THREAD

**Issue by vietqhoang** [WaniKani/WanaKana#24]
Confirmed with a Samsung S3 + Android 4.2 + Chrome 30.0.1599.105 and Nexus 5 + Android 4.4 + Chrome 30.0.1599.105

On the demo site, focus on IME input. Type in first character to translit, either single char or double char type characters. After transliteration, the cursor moves to the front. Subsequent transliteration results in the cursor placed in front of the first Japanese character that got transliterated.

Example with cursor represented as |

```
> h|
=> h|

> hi|
=> |ひ

> ra|ひ
=> ら|ひ

> らga|ひ
=> らが|ひ

> らがna|ひ
=> らがな|ひ
```

**Comment by DJTB** [comment]
Could not reproduce with Nexus 5, Android 4.4, Chrome 58
