### ISSUE TITLE
[Rekonq Kubuntu] Cursor is moving/resetting when typing.

### ISSUE THREAD

**Issue by zyaga** [WaniKani/WanaKana#25]
Example, typing しりぞく turns out as りしくぞ.

Here is my OS information:
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.1 LTS
Release:        12.04
Codename:       precise

(It's Ubuntu but with KDE)

Here is my browser information:
rekonq
Version 0.9.1
Using KDE Development Platform 4.8.4 (4.8.4)

**Comment by DJTB** [comment]
Closing since Rekonq appears to be abandoned (last update was in 2014) and is no longer default browser for KDE.

Willing to re-open if someone can provide a recent relevant example of the same issue.
