### ISSUE TITLE
ー should work with toHiragana (and toKatakana)

### ISSUE THREAD

**Issue by fasiha** [WaniKani/WanaKana#40]
`wanakana.toHiragana("ハツゴーリ")` doesn't convert anything to hiragana because of 'ー'. Will try to find a clean workaround.

Many congrats to @mimshwright on his/her new little one!

**Comment by DJTB** [comment]
Thanks for all your work! 

I included these changes in a recent update (4e7b6ffff59ee6dccbf14250b9e902ba70cfb309)
