### ISSUE TITLE
Standardize with Ruby mojinizer gem

### ISSUE THREAD

**Issue by johnnyshields** [WaniKani/WanaKana#41]
The Ruby mojinizer gem has some very solid romaji conversion logic that might resolve some of the issues here:
https://github.com/ikayzo/mojinizer/blob/master/lib/mojinizer/conversion.rb

**Comment by johnnyshields** [comment]
@polco @thoogeveen FYI this issue is relevant to the "ー" char not being converted by Wanakana (also https://github.com/WaniKani/WanaKana/issues/40)

**Comment by DJTB** [comment]
Closing due to punctuation/long char combo conversion improvements.
