### ISSUE TITLE
Windows Phone 8.1 — Double tapping first letter required to register

### ISSUE THREAD

**Issue by vietqhoang** [WaniKani/WanaKana#42]
Received the following email from a user:

```
This is a little, but annoying little bug.

Basically when I go to do reviews and start typing, the very first letter I hit is ignored every item. The only exception is the first review item behaves normally. 

Basically, this bug makes it so I have to double tap the first letter of whatever I'm trying to type before it will show up. It only happens on wanikani that I've noticed, and it started happening after the windows phone 8.1 update, which included a swipe keyboard (though I have it disabled).

I'm not sure if this is something you can fix or not, but I would appreciate it being looked into.
```

Unable to confirm since I do not have access to a Windows mobile phone.

**Comment by mimshwright** [comment]
I don't have one either. Technically, this is a WaniKani issue not a WanaKana issue. Sounds like there could be an issue where the entry field is losing focus after hitting the enter key or something?

**Comment by vietqhoang** [comment]
Ahh you are probably right. Missed the mention of the author isolating the issue. I'll see if I can obtain a Windows mobile phone and confirm the issue.

**Comment by jpkelly** [comment]
I have this same issue using an iPad Pro with a Smart Keyboard. Hitting the return ket when submitting an answer causes the entry field to lose focus.

**Comment by DJTB** [comment]
Received a similar query. Providing it here for more info.
I was unable to reproduce on browserstack with any of their 8.1 windows phone emulators though.

> Yesterday I used KW on my WP8.1 phone with the Edge browser and and noticed that the IME is ignoring the first letter. I remember that this issue was discussed somewhere. If I type "hyaku" the IME shows "やく", for the correct "ひゃく" I need to type "hhyaku". This happened with every word. It is manageable, but pretty annoying.

**Comment by DJTB** [comment]
This is an old issue reported back when WanaKana was v1.3.7.
Closing for now since it doesn't appear to be directly related to WanaKana's input handling.

Can be reopened if this is reproduced on a recent version and not just a case of host page rendering / form handling.
