### ISSUE TITLE
wanakana.toRomaji does not convert katakana to uppercase.

### ISSUE THREAD

**Issue by zachmcack** [WaniKani/WanaKana#47]
When using toRomaji to convert kana/katakana, it returns lowercase. 

I believe toRomaji should convert katakana to uppercase, and hiragana to lowercase, much like when using toKana. I'm considering making my own function for it, or editing WanaKana, but WanaKana should have this option. 

 If there is already a way for this, please do tell. Thanks!

**Comment by mimshwright** [comment]
That is not a bad idea. I think it should be an optional flag for that
function defaulting to the way it works now (e.g. uppercaseKatakana = false)
On Thu, Apr 14, 2016 at 04:40 zachmcack <notifications@github.com> wrote:

> When using toRomaji to convert kana/katakana, it returns lowercase.
>
> I believe toRomaji should convert katakana to uppercase, and hiragana to
> lowercase, much like when using toKana. I'm considering making my own
> function for it, or editing WanaKana, but WanaKana should have this option.
>
> If there is already a way for this, please do tell. Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WaniKani/WanaKana/issues/47>
>
-- 
Mims H. Wright

**Comment by zachmcack** [comment]
I agree. I actually assumed that it already has that optional parameter at first. I've been looking at the code but frankly, I'm not at that level yet. I'm hoping this gets implemented at some point, but this could also serve as a lesson for me.

**Comment by mimshwright** [comment]
Patched.
