### ISSUE TITLE
Romaji -> Kana

### ISSUE THREAD

**Issue by colakugel** [WaniKani/WanaKana#50]
In this sentence in Romaji "kore ga zenbu nonaka de ichiban warui", the output when i convert to Kana is
"これ が ぜんぶ のなか で いちばんわるい ", so the last space is missing. I wonder, why all other spaces were placed correctly, only this one not. Bug?

**Comment by mimshwright** [comment]
Hi @colakugel, did you type this into a text field to convert it or were you working with the API directly, i.e. by converting the whole string to kana at once?

If you typed this in, the first space after the 'n' converts the 'n' to ん so it actually takes two spaces to get the "ん␣"

**Comment by colakugel** [comment]
Hi@mimshwright, i used the API directly. wanakana.toKana("kore ga zenbu nonaka de ichiban warui")

**Comment by mimshwright** [comment]
In that case it's probably a bug! Do you want to try to fix it? If not, I'll have to get to it at some unknown date in the future.

**Comment by mimshwright** [comment]
Psych! I just fixed it. Please verify the fix!

**Comment by DJTB** [comment]
This should now be fixed as of [2.0.1](https://github.com/WaniKani/WanaKana/releases/tag/2.0.1)
