### ISSUE TITLE
Hiragana input problem on mobile keyboard

### ISSUE THREAD

**Issue by awcarroll** [WaniKani/WanaKana#51]
When entering hiragana on the keyboard, I just started having a new problem The English meaning input is fine, but the hiragana reading input is acting up. For instance, if I were entering the reading for 人, I would just enter in "hito" and I get what I want. But now, after I enter "hi", I end up with ひ on screen and highlighted. And since it is highlighted, when I enter "to", I get a と that has replaced my ひ. Now, I can't enter "to" until I tap after the ひ to unselect it. 

Here are my specs;
Android: 6.0.1
Device: Samsung Galaxy S5
Keyboard: Swype 1.8.23 (but also see same behavior with Samsung keyboard)
Browser: Chrome 55.0.2883.91

**Comment by awcarroll** [comment]
Some keyboards don't have this problem. Two that do not are Google and SwiftKey.

**Comment by vietqhoang** [comment]
This seems to be software keyboard dependent. May be worth investigating if it is possible to override the highlighting somehow.

**Comment by DJTB** [comment]
Hey @awcarroll I recently pushed a fix for Microsoft IME, and in fixing it we now ignore input during composition. It's possible it has fixed your issue as well. One can only hope :pray:

Could you try the first test input with Swype/Samsung Keyboard at http://wanakana.com/#ime and report back?

**Comment by awcarroll** [comment]
Sorry it took so long. I just tried it with my Swype keyboard and it works great.
-Alan

On Wednesday, August 2, 2017, 12:03:41 PM EDT, Duncan Bay <notifications@github.com> wrote:


Hey @awcarroll I recently pushed a fix for Microsoft IME, and in fixing it we now ignore input during composition. It's possible it has fixed your issue as well. One can only hope 🙏
 
Could you try the first test input with Swype/Samsung Keyboard at http://wanakana.com/#ime and report back?

**Comment by DJTB** [comment]
Better late than never :wink:, thanks for the feedback.
