### ISSUE TITLE
Problem to Bind with CKEDITOR

### ISSUE THREAD

**Issue by mah3uz** [WaniKani/WanaKana#52]
I am trying to bind Wanakana in CKEDITOR. But it doesn't work. Is it possible to bind with CKEDITOR?

**Comment by DJTB** [comment]
Not really unfortunately. CKEDITOR basically uses an entire webpage as the editor, filled with HTML markup for all the different text styles entered while editing.

Wanakana is designed to convert pure text (which is what input fields usually generate).

**Comment by mah3uz** [comment]
Thank you :)
