### ISSUE TITLE
Issues with double 'n' words

### ISSUE THREAD

**Issue by AlexAltea** [WaniKani/WanaKana#54]
(Hopefully this is not duplicated. I've seen many issues involving ん, but none matched my problem.)

The problem happens while typing ん followed by {な,に,ぬ,ね,の}. E.g. typing `onna`, I would expect "おんな" as output, but instead I get "おんあ".

This is specially troublesome as I have to remember to input a triple `n` every time.

**Comment by MasterKale** [comment]
Correct me if I'm wrong but don't most IMEs require you to double-tap 'n' to get ん? That's what I'm used to with the default IMEs on Windows and Mac.

**Comment by vietqhoang** [comment]
This is working as expected. Double tapping `n` or `n` + space will complete the `ん` transformation. It is done this way to leave out ambiguity.
