### ISSUE TITLE
Include full-width numbers in isJapanese()

### ISSUE THREAD

**Issue by DJTB** [WaniKani/WanaKana#63]
The current implementation of `isJapanese` will pass for kanji, kana, and zenkaku punctuation.
However the text `２０１１年` will fail due to the zenkaku numbers.

If `「！？ ` will pass as true, I think `１２３` should pass as well since numbers are likely to be paired with kanji anyhow. Normal characters like `[!?123` would continue to fail.

We still don't allow "ｗｉｄｅ　ｌａｔｉｎ" letters to pass - but numbers are neutral enough and they're used in Japanese text all the time like: ２月

I've made a PR to address this - just wanted to see if there were any objections to including the full-width numbers?

Ping @vietqhoang @mimshwright

**Comment by DJTB** [comment]
Actually, now I've thought about it further - I'll add all the relevant missing zenkaku/hankaku since they *will* appear in Japanese text - and should really pass `isJapanese`.

This method isn't used internally with IME conversion or any of the `toX` so I think it's safe to improve it.

Apart from some of the punctuation, most of these charcodes below are not currently included in the checks.
```
Full-width roman characters and half-width katakana ( ff00 - ffef)
  ff00   ＀  ！  ＂  ＃  ＄  ％  ＆  ＇  （  ）  ＊  ＋  ，  －  ．  ／ 
  ff10   ０  １  ２  ３  ４  ５  ６  ７  ８  ９  ：  ；  ＜  ＝  ＞  ？ 
  ff20   ＠  Ａ  Ｂ  Ｃ  Ｄ  Ｅ  Ｆ  Ｇ  Ｈ  Ｉ  Ｊ  Ｋ  Ｌ  Ｍ  Ｎ  Ｏ 
  ff30   Ｐ  Ｑ  Ｒ  Ｓ  Ｔ  Ｕ  Ｖ  Ｗ  Ｘ  Ｙ  Ｚ  ［  ＼  ］  ＾  ＿ 
  ff40   ｀  ａ  ｂ  ｃ  ｄ  ｅ  ｆ  ｇ  ｈ  ｉ  ｊ  ｋ  ｌ  ｍ  ｎ  ｏ 
  ff50   ｐ  ｑ  ｒ  ｓ  ｔ  ｕ  ｖ  ｗ  ｘ  ｙ  ｚ  ｛  ｜  ｝  ～  ｟ 
  ff60   ｠  ｡  ｢  ｣  ､  ･  ｦ  ｧ  ｨ  ｩ  ｪ  ｫ  ｬ  ｭ  ｮ  ｯ 
  ff70   ｰ  ｱ  ｲ  ｳ  ｴ  ｵ  ｶ  ｷ  ｸ  ｹ  ｺ  ｻ  ｼ  ｽ  ｾ  ｿ 
  ff80   ﾀ  ﾁ  ﾂ  ﾃ  ﾄ  ﾅ  ﾆ  ﾇ  ﾈ  ﾉ  ﾊ  ﾋ  ﾌ  ﾍ  ﾎ  ﾏ 
  ff90   ﾐ  ﾑ  ﾒ  ﾓ  ﾔ  ﾕ  ﾖ  ﾗ  ﾘ  ﾙ  ﾚ  ﾛ  ﾜ  ﾝ  ﾞ  ﾟ 
  ffa0   ﾠ  ﾡ  ﾢ  ﾣ  ﾤ  ﾥ  ﾦ  ﾧ  ﾨ  ﾩ  ﾪ  ﾫ  ﾬ  ﾭ  ﾮ  ﾯ 
  ffb0   ﾰ  ﾱ  ﾲ  ﾳ  ﾴ  ﾵ  ﾶ  ﾷ  ﾸ  ﾹ  ﾺ  ﾻ  ﾼ  ﾽ  ﾾ  ﾿ 
  ffc0   ￀  ￁  ￂ  ￃ  ￄ  ￅ  ￆ  ￇ  ￈  ￉  ￊ  ￋ  ￌ  ￍ  ￎ  ￏ 
  ffd0   ￐  ￑  ￒ  ￓ  ￔ  ￕ  ￖ  ￗ  ￘  ￙  ￚ  ￛ  ￜ  ￝  ￞  ￟ 
  ffe0   ￠  ￡  ￢  ￣  ￤  ￥  ￦  ￧  ￨  ￩  ￪  ￫  ￬  ￭  ￮  ￯ 
```

**Comment by vietqhoang** [comment]
No objections. I agree with with your assessment.
