### ISSUE TITLE
`toRomaji()` never translitterates `っ` to ltu

### ISSUE THREAD

**Issue by Mamonbo** [WaniKani/WanaKana#69]
When the input has "っ" followed by a Japanese character, the return repeats the first romaji character of the latter Japanese character.
But in some cases, it doesn't looks good.
```
あっ、 -> a,,     // Japanese punctuations
どっaと -> doatto   // The flag "nextCharIsDoubleConsonant" is still true.
                   // containing Latin character after っ. This input must be typo,though.
```
Is that your intended behavior? What do you think this function is to be used for?

**Comment by DJTB** [comment]
The "nextCharIsDoubleConsonant" is to allow Japanese IME input while still converting toKana - it's to handle differences between Microsoft and Google when converting toKana (they use っ differently).

It should probably be disabled for toRomaji though!

Could you provide some other examples to test conversion with?

For Example:
```
Input: あっ、
Expected: a,  (I'm not sure what you expect here)
Actual: a,,
```
I'm not sure what the intended input and output was for `どっaと` either :)

**Comment by DJTB** [comment]
> #### Kana without standardized forms of romanization
> There is no universally accepted style of romanization for the smaller versions of the y kana (ゃ/ャ, ゅ/ュ and ょ/ョ) when used outside the normal combinations (きゃ, きょ etc.), nor for the sokuon or small tsu kana っ/ッ when it is not directly followed by a consonant. Although these are usually regarded as merely phonetic marks or diacritics, they do sometimes appear on their own, such as at the end of sentences, in exclamations, or in some names. **The detached sokuon is sometimes represented as an apostrophe or as t; for example, あっ might be written as a' or at.**

#### Which do you think would be a more a reasonable result?
When っ is followed by non-kana char, it results in a single prime `'`
```
どっと -> dotto
どっaと -> do'ato
あっ、 -> a',
```

When っ is followed by non-kana char, it is discarded/ignored.
```
どっと -> dotto
どっaと -> doato
あっ、 -> a,
```

**Comment by Mamonbo** [comment]
Ignoring っ is not so bad;it is simple but in normal cases, it does not change the mean of sentences so much.

Btw, how about having an option or the second argument so that the users can choose how to treat this kind of っ?

**Comment by DJTB** [comment]
@Mamonbo we've made some changes, you can `npm install wanakana@beta` if you'd like to try out `toRomaji()` and give feedback.
