### ISSUE TITLE
MacOS native IME input composition

### ISSUE THREAD

**Issue by DJTB** [WaniKani/WanaKana#71]
User report regarding using IME input in a field with Wanakana active:

> On MacOS (sierra and high sierra) when using the Japanese/Hiragana input method, if the romaji I type has a suggestion in the list that is romaji and not kana, it makes it impossible to type in the answer field.

> For instance typing "ha" will have the first suggestion as literally "ha" then followed by 派，歯，... What I think happens is: as I tab through the suggestions, the OS puts "ha" into the input field, which wanakana then tries to convert to は, which in turn breaks the OS input suggestions completely and I can't progress down the suggestions list to the kanji input I want.

> I'm fairly certain it's due to Wanakana, because if I do the same thing in any other context, for instance the browser location bar, the suggestions show up, and I can progress from "ha" to 歯 and so on. That is my workaround when this happens, see this gif for a live example https://imgur.com/a/pnDk3

> In this example I am typing "ha", space, space, space. When in the answer field it inserts は, then highlights, then moves on.

> Then I move to the location bar and do the same again to progress past the troublesome option and I can get the kanji I want.

**Comment by DJTB** [comment]
Likely related to how the native IME handles composition events.
I'll do some debugging later today to gather more info.

**Comment by DJTB** [comment]
Holding off until we merge #70 since we'll have to do this testing for those changes anyway.

**Comment by DJTB** [comment]
Sorry for the long delay, this is a tricky pickle.
Seems React is having the same trouble. 
https://github.com/facebook/react/issues/8683

I can probably re-write the temporary workaround from that thread for use outside of React and within `bind()`.

Could you visit https://eyesofkids.github.io/ and try out your 'は' tab -> '歯' etc flow in the second input "uncontrolled". The red text is what you should monitoring, it shouldn't change until you choose your final selection. You might have to zoom the browser to ~150-200% (or just edit the font size/positioning css in devtools) or your IME composition box will probably cover the red text display.

**Comment by jimrhoskins** [comment]
I tried this out. I typed in `ha`, was able to tab through selections without triggering any change in the red text. I hit enter which collapsed the IME suggestion list, again no change in red text. The input is still selected indicating it is still composing. One final press of enter caused the red text to update, and puts the cursor at the end of the input. Seems to work as expected.

**Comment by DJTB** [comment]
@jimrhoskins Sorry to ask you again, but could you visit https://wanakana-device-test.firebaseapp.com

Ignore all the instructions and the form but try composing `ha` _at the bottom of the page in the **"Sandbox"** input_. Thanks!

**Comment by jimrhoskins** [comment]
@DJTB I tried composing the tricky words on the sandbox on that form, and it appears to work correctly. I was able to compose and tab past the `ha` suggestion into `歯` without wanakana interfering. That field works as I would expect it to 👍 🎉 

Thanks for working on this!
