### ISSUE TITLE
Text showing non encoded in chrome and firefox

### ISSUE THREAD

**Issue by jking6884** [WaniKani/WanaKana#72]
![image](https://user-images.githubusercontent.com/4825257/32130938-5e8107a4-bb70-11e7-8995-7c6d4b188a3f.png)

this is the code I used

```
<textarea id="ime" autocapitalize="none" autocorrect="none" autocomplete="off"></textarea>
<script src="node_modules/wanakana/lib/wanakana.min.js"></script>
<script>
var input = document.getElementById('ime');
wanakana.bind(input);
</script>
```

**Comment by DJTB** [comment]
Can you show your whole html file?
That looks like a unicode display issue.

You might need `<meta charset="utf-8">` in the `<head></head>` of your html.

**Comment by jking6884** [comment]
Thanks @DJTB
