### ISSUE TITLE
Charset/Encoding configuration question

### ISSUE THREAD

**Issue by aaron13100** [WaniKani/WanaKana#73]
I'm trying to do romaji to hiragana. Here is the code I'm using.

```
<html>
<script src="te_form-quiz_files/wanakana.min.js"></script>
<body>
<textarea id="ime" autocapitalize="none" autocorrect="none" autocomplete="off"></textarea>
<script>
	var input = document.getElementById('ime');
	wanakana.bind(input);
</script>
</body>
</html>
```

When I type "su" I get this result (the characters ã™ appear).
![screen shot 2017-12-11 at 10 02 42 am](https://user-images.githubusercontent.com/16979849/33843389-7aa353a8-de5a-11e7-941b-d22a69a41e78.jpg)

So two characters appear where there should be す

"sumimasen" becomes ã™ã¿ã¾ã›ã‚“
![screen shot 2017-12-11 at 10 04 09 am](https://user-images.githubusercontent.com/16979849/33843460-ad6ea8be-de5a-11e7-8921-e387a50c394c.jpg)

It seems like a charset setting issue?

thanks

**Comment by vietqhoang** [comment]
You need a UTF-8 meta tag, I think.

`<meta charset="UTF-8">`

**Comment by aaron13100** [comment]
Correct. It works now.

**Comment by aaron13100** [comment]
thanks
