### ISSUE TITLE
Wanakana website / toKana not working in UC Browser 6.2 (Edge kernel) for Win 10

### ISSUE THREAD

**Issue by halfsprit** [WaniKani/WanaKana#77]
I open the website wanakana.com in Win10 IE ，it doesn't work, can't conver romaji to kana.

**Comment by DJTB** [comment]
Which version of IE are you using? 
You can get all the details here: https://whichbrowser.net/

**Comment by halfsprit** [comment]
I use UC(http://www.uc.cn/) browser and switch the kernel to IE，wanakana can't conver romaji to kana.

You are using UC Browser 6.2 on Windows 10

Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0; UBrowser/6.2.3964.2) like Gecko

It works ok in original EDGE browser，but it seems that can't work in browser use IE/Edge kernel, I create a program using ie kernel, wanakana don't work.

**Comment by DJTB** [comment]
Can you try saving the following as `test.html` and opening it in UC browser?
It's worth checking if the problem is actually with the demo website or Wanakana.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://unpkg.com/wanakana" /></script>
    <style> #ime { height: 2rem; line-height: 2.5rem; font-size: 1.5rem; } </style>
  </head>
  <body>
    <input id="ime" type="text" lang="ja" autocapitalize="none" autocorrect="none" autocomplete="off" />
    <script> wanakana.bind(document.getElementById('ime')); </script>
  </body>
</html>

```

**Comment by halfsprit** [comment]
No, it still can't work.

**Comment by DJTB** [comment]
Hmm, does it work on mobile? UC Browser on Android?

If it doesn't work on UC Android either, could you try the developer edition http://www.uc.cn/business/developer/ so we can see what errors are happening in the console?

**Comment by halfsprit** [comment]
It works in UC Browser on Android.
It's can't work in all browsers using IE/Edge kernel like QQ Browser, 2345 Browser etc. neither IE11 nor Edge kernel, but it can work in Original Edge

**Comment by DJTB** [comment]
Thanks for the information. A group of users has volunteered to test on different devices for me and I'm setting up a proper test page with error logging/ reporting. When that is ready I'll let you know here so you can try again.

**Comment by DJTB** [comment]
@halfsprit Can you visit https://wanakana-device-test.firebaseapp.com/ and try input *at the bottom of the page in the "Sandbox" input*

It will probably error straight away when you visit - but I'll receive a full stack trace to find out what is breaking on UC Browser.

**Comment by halfsprit** [comment]
I input watashifa，it convert to わたしふぁ，then the website stops work.

**Comment by DJTB** [comment]
Can you please check on [wanakana.com](wanakana.com) website again.
It works with IE11 now with polyfills, so hopefully UC Browser doesn't have other features missing.

**Comment by halfsprit** [comment]
thanks

**Comment by DJTB** [comment]
:+1:
