### ISSUE TITLE
Incorrect toRomaji conversion for katakana with long vowels (ー)

### ISSUE THREAD

**Issue by elusiveunit** [WaniKani/WanaKana#79]
Edit: doing the easiest thing last of course, a test that fails on master:

```javascript
describe('Long vowels', () => {
  expect(toRomaji('スーパー')).toBe('suupaa');
});
```

---

When running `toRomaji('スーパー')` I get the expected 'suupaa' on wanakana.com, but when doing it with the npm version (2.3.4) I get 'su-pa-'. Minimal repro, try toggling the script tags:

**package.json**
```json
{
  "dependencies": {
    "wanakana": "~2.3.4"
  }
}
```

**index.html**
```html
<!DOCTYPE html><html><head><meta charset="utf-8">

<script src="http://wanakana.com/assets/js/wanakana.min.js"></script>
<!--<script src="node_modules/wanakana/lib/wanakana.min.js"></script>-->
<script>console.log(wanakana.toRomaji('スーパー'));</script>

</head><body></body></html>
```

Also cloned master, ran `npm run build` and used the created `WanaKana/dist/lib/wanakana.min.js` with the same result.

**Comment by DJTB** [comment]
Oof, good catch. It appears that the 3.0 beta API docs and min.js were accidentally copied to the gh-pages branch (despite it saying 2.3.4). I'll fix that back to 2.3.4 now.

The 2.x versions always convert `ー` to `-` regardless of kana type.
```
it("Doesn't mangle the long dash 'ー' or slashdot '・'", () =>
  expect(toRomaji('罰ゲーム・ばつげーむ')).toBe('罰ge-mu/batsuge-mu'));
```
In 3.x this behaviour is indeed remedied to what you expected (and saw on demo site):
```
  it("Doesn't mangle the long dash 'ー' or slashdot '・'", () =>
    expect(toRomaji('罰ゲーム・ばつげーむ')).toBe('罰geemu/batsuge-mu'));
```

I'm about to do some user testing with 3.0 and shouldn't be too long before it's published. You can try it out with `npm i wanakana@next` if you'd like - the remaining testing / potential issues are with `bind` and `IMEMode`.

**Comment by elusiveunit** [comment]
I see, thanks! I'll run with the 3.0 beta when it's available (currently getting 'No matching version found for wanakana@next In most cases you or one of your dependencies are requesting a package version that doesn't exist.').

**Comment by DJTB** [comment]
Oh sorry, yarn gives you a list to select from but npm doesn't.
You can try `npm i wanakana@3.0.2-beta.2` or wait for it to be released fully to npm.

**Comment by elusiveunit** [comment]
Ah, TIL. Apparently npm requires `next` to be a published tag for `@next` to work.
