### ISSUE TITLE
Convert kanji characters to Romaji

### ISSUE THREAD

**Issue by sharathvignesh** [WaniKani/WanaKana#81]
I was using `toRomaji` API to convert characters to Romaji. While Hiragana and katakana were successfully converted, I found that the kanji characters did not get converted to Romaji. Is there any way to get around this ?

**Comment by DJTB** [comment]
Kanji only has a reading depending on its context, or rather, which word that kanji is being used in.
Wanakana doesn't analyse the semantic content (the meaning) of the input you provide, it only [transliterates](https://en.wikipedia.org/wiki/Transliteration).

You can try [Kuroshiro](https://github.com/hexenq/kuroshiro.js) which uses Wanakana along with [Kuromoji](https://github.com/takuyaa/kuromoji.js). However, you won't achieve 100% accuracy. For example, 一人 will commonly be presented as いちにん even in a situation where it most likely represents ひとり.

**Comment by vietqhoang** [comment]
I believe [Ve](https://github.com/Kimtaro/ve) has a JS library which may do kanji -> kana. Something to look into. It is a project by Kim of [jishi.org](https://www.jisho.org).

**Comment by DJTB** [comment]
@sharathvignesh No problem, best of luck!
Here's a fun one with 5 different readings of  to think about: "3月1日は日曜日で祝日、晴れの日でした"

**Comment by sharathvignesh** [comment]
I found [Mecab](https://github.com/hecomi/node-mecab-async) which was good too. It converts them to Katakana, from which I was able to convert it to romaji using WanaKana's toRomaji.

**Comment by retorquere** [comment]
The JS version of Ve only connects by http to the ruby version if I'm reading it correctly. It's not usable without that ruby server running I think. mecab executes an executable, so also not usable in a pure-js environment.
