### ISSUE TITLE
[QUESTION] How it works?

### ISSUE THREAD

**Issue by loretoparisi** [WaniKani/WanaKana#85]
Hello I'm contributing to [kakasi.js](https://github.com/loretoparisi/kakasi.js) as simple kanji kana inverter based on [kakasi](http://kakasi.namazu.org/index.html.en), mostly used to convert to romanji. I would like to combine this with WanaKana. Now kakasi is using SKK [dictionaries](https://github.com/skk-dev/dict)  and rules. I don't find details how WanaKana works for romaji to kanji inversion, that it seems pretty good as output. I have also recently posted a [question](https://stackoverflow.com/questions/52532440/skk-for-kana-to-kanji-inverter) on SF about [libskk](https://github.com/ueno/libskk), maybe WanaKana could be a good alternative for this, if you can confirm.

Thank you in advance.

**Comment by DJTB** [comment]
WanaKana is only for hiragana/katakana/romaji input, it is not intended to convert to/from kanji. It's a very literal converter: `aiueo = あいうえお`

It _mainly_ works by following trees `k -> y -> o -> u : きょう` though there's a lot of edge cases which complicate things :)

You could take a look at these for kanji -> kana/romaji, both of which use dictionaries:
* Java: https://github.com/atilika/kuromoji
* JS port: https://github.com/takuyaa/kuromoji.js

**Comment by DJTB** [comment]
Oh, I just noticed that kanji was mentioned at the start of the readme.

I think that was there because we include helpers like `isKanji()` but we don't actually provide any conversion methods for kanji.

I've updated that to be clearer now. Sorry for any confusion!

**Comment by loretoparisi** [comment]
@DJTB thanks a lot, we have just passed the output to a native speaker, and she realized that it was in that way! So functions like `isKanji()` are not implemented?

**Comment by DJTB** [comment]
`isKanji()` is implemented, but it is a strict check so 銀行 is true but お茶 and 深い are false.
Unfortunately I don't think it can help you very much. 
It is more for text/input handling and converting.
