### ISSUE TITLE
how can I get ぢ: 'ji', づ: 'zu' ? 

### ISSUE THREAD

**Issue by ishigamii** [WaniKani/WanaKana#86]
Hi, first thanks for the library that is very nicely done 👍 
I am just having trouble with this little thing as in the past lib I was using I was about to get those two caracteres as they were "dji" and "dzu". 

I am asking the library to translate from romanji "ji" and I always get the other "ji" : じ same for "zu" is there any way to get the other one : ぢ ? I saw that you have a custom mapping for the other methods but not for this one so I am wondering how I can achieve that. 

Thanks a lot.

**Comment by DJTB** [comment]
Which methods are you trying to use? 
I'm not sure that I understand what you would like to achieve.
Some examples might help.

This works fine for me: 
```javascript
toKana('jizu', { customKanaMapping: { ji: 'ぢ', zu: 'づ' } })
// -> 'ぢづ'
toRomaji('ぢづ', { customRomajiMapping: { ぢ: 'ji', づ: 'zu' } })
// -> 'jizu'
```

**Comment by ishigamii** [comment]
I thought the following wasn't possible but it is working so I will close this issue sorry. 
```
toHiragana('jizu', { customKanaMapping: { ji: 'ぢ', zu: 'づ' } })
```
